<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCore)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AnimationSystem.Types">
      <HintPath>$(GameManaged)\AnimationSystem.Types.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManaged)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCore)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(BepInExCore)\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$(BepInExCore)\MonoMod.RuntimeDetour.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManaged)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(GameManaged)\UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManaged)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KmyTarkovReflection\KmyTarkovReflection.csproj" />
  </ItemGroup>

</Project>
